.catalog:
  name: Vault
  version: "0.6.0-rancher1"
  minimum_rancher_version: v0.56.0
  uuid: vault-0.6.0
  questions:
    - variable: instances
      label: "Vault instances"
      description: "Number of Vault instances in HA cluster"
      type: int
      required: true
      default: 2
    - variable: tls_support
      label: "TLS / SSL support"
      description: "Enable TLS / SSL support for Vault configuration"
      required: true
      type: boolean
    - variable: backend
      label: "HA backend service"
      description: "HA backend"
      required: true
      type: enum
      default: "consul"
      options:
        - consul
        - zookeeper
    - variable: cert
      label: "TLS / SSL server certificate"
      description: "Vault server certificate for TLS / SSL support"
      required: false
      type: multiline
    - variable: backend_service
      label: "External link service"
      description: "Vault HA backend service link"
      required: true
      type: service
    - variable: key
      label: "TLS / SSL server key"
      description: "Vault private key for TLS / SSL support"
      required: false
      type: multiline
    - variable: vault_port
      label: "Vault port"
      default: 8200
      description: "Vault port exposed for host communication"
      required: true
      type: int
    - variable: backend_port
      label: "HA backend port"
      required: true
      type: int
      default: 8500
vault:
  scale: ${instances}
  metadata:
    tls_support: ${tls_support}
    cert: ${cert}
    key: ${key}
    backend: ${backend}
    backend_service: ${backend_service}
    port: ${vault_port}
    backend_port: ${backend_port}
vault-config:
  scale: ${instances}
vault-data-volume:
  scale: ${instances}
